### ISSUE TITLE
Unexpected latency spikes

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#11164]
**Describe the bug**

Since this week we have new benchmarks running, which allow us to test with process execution latency.

We can see that on avg a process instance execution is about ~100-250 ms, with one Task and one worker (completing this after some milliseconds sleep).

Interesting is that from time to time the process execution latency spikes up to several seconds

![latency-spikes2](https://user-images.githubusercontent.com/2758593/205327742-35557103-b225-4cbc-8e0b-ec8226b48f64.png)
![latency-spikes](https://user-images.githubusercontent.com/2758593/205327752-3f6273fa-1db7-45e0-a6f0-c9fff4d75681.png)

This can be seen in several medic benchmarks, so this is likely to happen and easy to reproduce.

I think this is related to things which other users have reported like:

https://forum.camunda.io/t/zeebe-is-unreasonably-slow-with-out-of-the-box-setup/41156?u=zelldon

**To Reproduce**
Run a new latency benchmark.

**Expected behavior**

Stable latency over time.

**Environment:**
- OS: 
- Zeebe Version: 8.1.x
- Configuration: 

**Notes:**
- suspected to be the cause for backpressure spikes, see [SUPPORT-15898](https://jira.camunda.com/browse/SUPPORT-15898)

**Comment by npepinpe** [comment]
I know Falko had this with segment pre-allocation, but it was pretty regular in their case. Could still be a hint of what's happening (if we can correlate this with when we create segments).

**Comment by Zelldon** [comment]
With @deepthidevaki new medic benchmark dashboard we can see over several benchmarks/weeks also big spikes (up to 10 s), and smaller ones. The bigger might be related to restarts of course, but it is also often between 400-2.5 s 
![latency](https://user-images.githubusercontent.com/2758593/210038790-264b5c8b-a449-4331-ab7f-a1974f3e2273.png)

**Comment by Zelldon** [comment]
@deepthidevaki since you are right now looking at async flush and related latency things, would be nice if you can share any findings around that if you have any :)

**Comment by Zelldon** [comment]
Might be related to https://github.com/camunda/zeebe/issues/11107 :thinking:

**Comment by megglos** [comment]
Got resolved with https://github.com/camunda/zeebe/issues/11444

**Comment by Zelldon** [comment]
It is not resolved (@megglos )

Latest medic weekly benchmark for latency (running one instance at a time).

![segment](https://user-images.githubusercontent.com/2758593/216915472-4f9064f1-c65f-4250-bd6b-6132b24b74f7.png)

**Comment by npepinpe** [comment]
Looking at the latest benchmark, we see spikes to 10s every once in a while, which coincide with leader changes. I'll keep looking at other benchmarks to see if this is always the case. This is not too unexpected for me, as long as it recovers fairly quickly.

**Comment by megglos** [comment]
Hint for the engineer to follow-up, [here](https://docs.google.com/document/d/1sxC_Q-tQqv7YmjEAJZgif7vjUzdkUD5m4iZwTUYixWo/edit#bookmark=id.2jiagd29xo5q) are notes on the observations at the customers setup during the onsite.

The prototype used during this test contained the following changes:
https://docs.google.com/document/d/1sxC_Q-tQqv7YmjEAJZgif7vjUzdkUD5m4iZwTUYixWo/edit#bookmark=id.dhm988scm96f
and was build from this branch:
https://github.com/camunda/zeebe/tree/81-prototype-2

**Comment by Zelldon** [comment]
@megglos and I had a small discussion around that topics and agreed on that we will take a look at it on Wednesday, we have to complete other work before.

**Comment by Zelldon** [comment]
Right now our assumption is that it might be related to rocks db, and that a fix for #11813 might resolve this as well. We should verify that afterward of course again.

**Comment by Zelldon** [comment]
We still see that in our medic benchmarks

![latency](https://github.com/camunda/zeebe/assets/2758593/50d91b03-38cc-4b04-9498-8cede559e12b)

**Comment by deepthidevaki** [comment]
@Zelldon Have you verified that these spikes are not correlating to leader changes?

**Comment by Zelldon** [comment]
Not yet. I hoped someone will do that which takes care of the issue. I have to many stuff on the medic plate right now.

**Comment by oleschoenburg** [comment]
I sampled a couple of latency spikes, all related to role changes. I'm closing this issue, I don't think we have unexpected latency spikes anymore.
