### ISSUE TITLE
Standalone gateways are failing with error code 3 on all release benchmarks

### ISSUE THREAD

**Issue by Zelldon** [camunda/zeebe#13949]
**Describe the bug**

I was checking the release benchmarks to assess https://github.com/camunda/zeebe/issues/13948 and was observing that all benchmarks have gateways which are restarted at least once.

All with the same error code: 3.

```
$ kgpo
NAME                                           READY   STATUS      RESTARTS         AGE
camunda-platform-curator-28205895-bqg9z        0/1     Completed   0                7m1s
elasticsearch-master-0                         1/1     Running     0                10h
elasticsearch-master-1                         1/1     Running     0                17h
elasticsearch-master-2                         1/1     Running     0                4d21h
leader-balancer-28205895-kqsms                 0/1     Completed   0                6m57s
release-8-1-x-zeebe-0                          1/1     Running     2 (7d11h ago)    33d
release-8-1-x-zeebe-1                          1/1     Running     4 (8d ago)       33d
release-8-1-x-zeebe-2                          1/1     Running     1 (19d ago)      33d
release-8-1-x-zeebe-gateway-5476565f47-lk4b8   1/1     Running     45 (6d22h ago)   33d
release-8-1-x-zeebe-gateway-5476565f47-zppwx   1/1     Running     45 (6d23h ago)   33d
starter-5c84cd5dc5-24s2k                       1/1     Running     0                17h
worker-7c57666cdd-6jwfp                        1/1     Running     0                7d21h
worker-7c57666cdd-9wfm2                        1/1     Running     0                7d16h
worker-7c57666cdd-zxmr2                        1/1     Running     0                3d21h


    Last State:     Terminated
      Reason:       Error
      Exit Code:    3
      Started:      Fri, 11 Aug 2023 10:06:18 +0200
      Finished:     Fri, 11 Aug 2023 13:27:43 +0200

```

⚠️ This is not visible in the Grafana dashboard. It looks like that even in the medic benchmarks at least one gateway failed (but due to oom), this is not visible in our dashboard either.

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: all versions ?
- Configuration:

**Comment by megglos** [comment]
ZDP-Triage:
- also recently affected job push benchmarking 
- impacts latency and throughput if it happens to often
- should investigate asap

**Comment by oleschoenburg** [comment]
Already investigated by @npepinpe: https://github.com/camunda/zeebe/issues/13948#issuecomment-1757856391

I think this one can be closed for the same reason: Gateways were getting killed occasionally because they were using more than the requested memory.

**Comment by megglos** [comment]
@oleschoenburg might it make sense here to actually follow-up with an issue to revise the controller (and helm chart) or the cluster plans to set request==limit? 🤔

**Comment by oleschoenburg** [comment]
@megglos Yeah I can do that :+1: Benchmarks are already fixed: https://github.com/zeebe-io/benchmark-helm/pull/90

**Comment by Zelldon** [comment]
@oleschoenburg @megglos release-8.1 benchmarks are still failing with [the same error](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22release-8-1-x%22%0Alabels.k8s-pod%2Fapp%3D%22camunda-platform%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fcomponent%3D%22zeebe-gateway%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22release-8-1-x%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fmanaged-by%3D%22Helm%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe-gateway%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fpart-of%3D%22camunda-platform%22%0A-jsonPayload.message%3D%22Stream%20Error%22;pinnedLogId=2024-03-24T13:56:01.095911718Z%2Fu0i5oo9vqx2blk60;cursorTimestamp=2024-03-24T13:56:12.114088080Z;duration=P1D?project=zeebe-io) (OOM).

```
INFO 2024-03-24T13:55:54.317710074Z release-8-1-x-zeebe-gateway-79ccdd5d7c-9tv9n - Failed to probe release-8-1-x-zeebe-gateway-79ccdd5d7c-l585z
INFO 2024-03-24T13:56:01.095911718Z Terminating due to java.lang.OutOfMemoryError: Java heap space
ERROR 2024-03-24T13:56:02.300001061Z + hostname -i
ERROR 2024-03-24T13:56:02.300058673Z + HOST=10.0.5.4
```

```
$ kgpo
release-8-1-x-zeebe-gateway-79ccdd5d7c-9tv9n                      1/1     Running     3 (19h ago)   32h
release-8-1-x-zeebe-gateway-79ccdd5d7c-l585z                      1/1     Running     4 (19h ago)   32h
```


```
    Last State:     Terminated
      Reason:       Error
      Exit Code:    3
      Started:      Sun, 24 Mar 2024 09:14:59 +0100
      Finished:     Sun, 24 Mar 2024 14:56:24 +0100
```
